### ISSUE TITLE
Compatibility  with redux

### ISSUE THREAD

**Issue by jdkanani** [firebase/reactfire#114]
No sure if this is right way to go ahead but any support for redux + firebase would be great. Currently reactfire starts listening in component. Redux will change it.

After redux, every component will dispatch an action (to subscribe/unsubscribe) to firebase and get notified when store changes. That way many components may get cached data which store already has before subscribing (for further  changes) - this will remove flicker in UI.

**Comment by prescottprue** [comment]
@jdkanani There are a few libraries that help with this, [redux-firebasev3](https://github.com/prescottprue/redux-firebasev3) is one that I created based on [redux-react-firebase](https://github.com/tiberiuc/redux-react-firebase). #38 is a pretty good discussion on this too since the a nice way to implement redux stuff is through Higher Order Components.

**Comment by jdkanani** [comment]
@prescottprue Thanks.
