### ISSUE TITLE
Impossible to rebind on propsDidUpdate

### ISSUE THREAD

**Issue by ProLoser** [firebase/reactfire#31]
I want to use `react-router` which does not rebuild the components if you simply change a `:recordId` token in the url. This is making it difficult for me because I'm trying to use this mixin to handle a lot of the firebase heavy lifting but I'm binding to a URL based on the route token.

Do you suggestion I just bind to the base of my application (which makes me concerned that I will be subscribing to events and updates other users make on sections of the that I don't care about) or is there a way to 'adjust' the binding after-the-fact?

**Comment by jwngr** [comment]
Hey there, thanks for the question. I'm not sure I completely understand the problem you are running into. It's probably because I've never used `react-router`, so please bear with me. Every time you change the URL and have a new `:recordId`, do you want ReactFire to sync new data for that specific `recordId`? Is there a way to get a signal when the `recordId` changes and manually recreate your component?

I wouldn't suggest binding to the root of your Firebase since, as you mentioned, that will result in a lot of wasted bandwidth. Once I know a bit more about your use case, I can hopefully offer some guidance.

**Comment by ProLoser** [comment]
I need to be able to rebind on props change. The props tell me what to watch, but this plugin seems to only work if you bind at the `componentWillMount` phase. How can I essentially change what URL it's bound to after the component has mounted?

**Comment by jwngr** [comment]
> this plugin seems to only work if you bind at the componentWillMount phase

I don't think this is strictly true. You should be able to call `this.bindAsArray()` or `this.bindAsObject()` from any method in your React component, not just `componentWillMount()`.

Once your props change, can you call `this.unbind(someVar)` to end the current binding and then `this.bindAs*(newRef, someVar)` to initiate a new binding? I don't know how efficient that will be, but that should work.

**Comment by ProLoser** [comment]
Is there a more efficient alternative to binding in multiple components so I don't have to bind/unbind in every single one?

**Comment by jwngr** [comment]
Performance-wise, binding to the same Firebase reference in multiple components is not going to hurt you since Firebase will internally cache that data for you. It is a bit annoying code-wise, but you should feel comfortable doing that. If you can put together a live repro of what you are trying to do so I have a better understanding of your use case, I will take a look and try to offer some guidance.
