### ISSUE TITLE
Add the Firebase key to array items

### ISSUE THREAD

**Issue by jwngr** [firebase/reactfire#37]
Currently, there is no way to get the Firebase key (aka push ID) for items bound via `bindAsArray()`. We should adopt a solution like [AngularFire's `$toJSON()` method](https://github.com/firebase/angularfire/blob/1d3260937fd5af0708d7a60795b83361dc943a29/src/utils.js#L403-L432) which handles both arrays of objects and arrays of primitives. In the case of objects, we do something very similar to what you have done. In the case of a primitive, we set the array items as objects with `$value` (i.e. the primitive value) and `$id` (the Firebase key).

**Comment by jwngr** [comment]
Initial attempt: #35

**Comment by matiaslarsson** [comment]
Yes please! Any progress on this?

**Comment by jwngr** [comment]
Haven't had time to code this up yet. There were some attempts from the community (#35 and #40) but neither fully solved the problem. Still on my todo list.

**Comment by mrienstra** [comment]
Stating the obvious here, but since this didn't immediately occur to me, perhaps it will be helpful to others:

You can use the `bindAsObject` method in place of `bindAsArray`.

Related: the [limitations of treating Firebase objects as arrays](https://www.firebase.com/docs/web/guide/understanding-data.html#section-arrays-in-firebase).

PS: If you were using `Array.prototype.map` to turn your Firebase arrays into arrays of React elements, a lazy way to instead map objects is to use [lodash's `mapValues`](https://lodash.com/docs#mapValues).

**Comment by AndrewBestbier** [comment]
This was done in #40

**Comment by jwngr** [comment]
Yup, this got merged in. I'll get a 0.2.0 release out with all the new goodies in the next day or two.
