### ISSUE TITLE
Upgrading to 0.5.0 throws: this.state.newsItems is already bound to a Firebase reference

### ISSUE THREAD

**Issue by matiaslarsson** [firebase/reactfire#49]
So I'm probably doing something wrong? In 0.4.0 the code below worked fine when filtering a news list by year but now Reactfire is complaining that newsItems is already bound to a Firebase reference.

```
componentDidMount: function() { // INITIAL LOAD
    this.getNewsList(this.props.query.year);
},
	
componentWillReceiveProps: function (newProps) { // FILTERING
    this.getNewsList(newProps.query.year);
},

getNewsList: function(filterYear) {
    var newsItemsRef = this.firebaseRefs["newsItems"] || new Firebase("https://XXXXXXXXXX.firebaseio.com/news");
		
    if(filterYear) {
        this.bindAsObject(newsItemsRef.orderByChild("_year").equalTo(parseInt(filterYear)), "newsItems");	
    }
    else {
        this.bindAsObject(newsItemsRef.orderByPriority(), "newsItems");
    }	
}
```

The two examples you have (Todo and Comments) never refresh/filter an existing array/object (only updating or deleting from it) so I'm wondering if you can point me in the right direction? Am I supposed to unbind the list before refreshing it? (This will make the list flash to empty before it's filled, something I'd like to avoid)

```
componentWillReceiveProps: function (newProps) { // FILTERING
    this.unbind("newsItems");
    this.getNewsList(newProps.query.year);
},
```

**Comment by jwngr** [comment]
Interesting. I did make a change which disallowed binding to something which was already bound to (which kind of makes sense to me), but maybe that was the wrong decision. I see what you are saying and your use case makes sense. It'll be a bit tricky since I'll need to clear the existing listeners if they exists, but I'll go ahead and put together a 0.5.1 release which reverts that change and it should fix your issue. I'm about to go on vacation so I can't guarantee it'll happen soon, but I'll try to get to it.

**Comment by jwngr** [comment]
Also, for what its worth, it probably makes sense to just use client-side filtering of the downloaded data stored in `this.state.newsItems` instead of constantly re-binding via ReactFire. Every time you re-bind, you re-download the data and you'll see the flash you mentioned. The only reason you didn't see that in 0.4.0 is because of a bug which never called `off()` on the previously bound listeners. I am not going to re-introduce that behavior. So your best bet here is to just download all the data and do the ordering / filtering client-side.

**Comment by jwngr** [comment]
And after thinking about this more, I don't think I really want to change this behavior. Under the hood, I'm going to be unbinding the variable before re-binding, so I think it makes sense to require the caller to do that so they understand the performance implications of what they are about to do. I updated [the change log](https://github.com/firebase/reactfire/releases/tag/v0.5.0) with this breaking change so that future devs don't run into it. Sorry if it's caused you troubles. Thankfully, if you just do client-side filtering with something like [lodash](https://lodash.com/docs), you should see better performance and easier code.

**Comment by matiaslarsson** [comment]
OK, I really liked that bug in 0.4.0. ;)

Client side filtering will work for my particular use case but people wanting to query a very large Firebase structure (or very slow mobile clients or connections) will probably want to get the results filtered from Firebase so you might want to revisit this sometime.

**Comment by jwngr** [comment]
Haha yeah it was a nice bug that was doing bad things under the hood :)

I definitely do see people wanting to change their query parameters, so I will keep this in mind and see how many others run into issues. It may make it's way back in before the 1.0.0 release. Thanks for opening this issue and thanks for the feedback!

**Comment by matiaslarsson** [comment]
Awesome, keeping my fingers crossed for a solution in 1.0.0!

Have a nice vacation!
