### ISSUE TITLE
Why '.key' and '.value'?

### ISSUE THREAD

**Issue by timotius02** [firebase/reactfire#55]
Just wanted to know why the use of '.key' and '.value' rather than just 'key' & 'value'. Also why does reactfire bind work like:

```json
[
  {
    ".key": "-Jtjl482BaXBCI7brMT8",
    ".value": 100
  },
  {
    ".key": "-Jtjl6tmqjNeAnQvyD4l",
    "first": "Fred",
    "last": "Flintstone"
  },
  {
    ".key": "-JtjlAXoQ3VAoNiJcka9",
    ".value": "foo"
  }
]
```
instead of just:
```json
[
  {
    "-Jtjl482BaXBCI7brMT8" : 100
  },
  {
    "-Jtjl6tmqjNeAnQvyD4l": { 
       "first": "Fred",
       "last": "Flintstone"
      }
  },
  {
    "-JtjlAXoQ3VAoNiJcka9" : "foo"
  }
]
```

**Comment by jwngr** [comment]
There are a couple reasons why I went we `.key` and `.value`. For one, `.value` is already a built-in thing to Firebase and you can actually do something like this:

```
ref.set({ '.value': 'foo' });
```

which is equivalent to:

```
ref.set('foo');
```

So using that built-in seemed to make a lot of sense. While `.key` is not a built-in, it follows the same naming convention.

Regarding your suggestion to use `key` and `value`: those are very common names for nodes and would most certainly clash with existing user data. If you tried to sync a node which had a `key` or `value` child, then ReactFire would be overwriting that data, which would be unexpected and a bad developer experience. Using `.key` and `.value` (both of which are not valid Firebase keys) ensures that user data will not be overwriting by the mixin.

Finally, regarding your suggestion for how the data is structured, I don't think adding that extra layer of nesting makes a lot of sense in practice. Imagine if you wanted to get the first array item. In order to read the data, you would have to do something like this:

```
var firstItemObj = this.state.items[0];
var firstItemKey = Object.keys(firstItemObj)[0];
var firstItem = firstItemObj[firstItemKey];
```

That is a very roundabout way of doing things. With the existing implementation, all you need to do is:

```
var firstItem = this.state.items[0];
```
