### ISSUE TITLE
The connection is really slow on react-native (ios)

### ISSUE THREAD

**Issue by olivierlesnicki** [firebase/reactfire#77]
For some reasons, it takes a long time for my react-native app to `connect` to `firebase` (i.e. receives the first event). Once the connection has been made, any subsequent events are triggered correctly with close to no latency.

Is there a reason why that would happen? (for example, Heroku sends dyno to sleep if no one uses them and spins them up when someone tries to access it. This means the first connection often takes much longer than the subsequent one)

**Comment by katowulf** [comment]
Could you provide some evidence demonstrating what "a long time" means, and offer a minimal repro that we can use to test? Output from Firebase.enableLogging(true) would be very helpful.

**Comment by katowulf** [comment]
It would also help to know if this is specific to heroku and, if so, why react native is involved in the equation.

**Comment by olivierlesnicki** [comment]
@katowulf it has nothing to do with Heroku and all to do with react-native.

I was just trying to give an example of a service that can be very slow on the first connection and then very fast on subsequent ones.

**Comment by jwngr** [comment]
What version of React Native are you using? With 0.15, the React team released a bunch of new websocket fixes which may improve the situation. Likewise, maybe something they implemented made the situation worse. The output from turning on `Firebase.enableLogging(true)` at the beginning of your app will be useful for us. Without that, there's not a ton we can do to help.

Also, note that I'm making this with the `invalid` tag since this is a Firebase problem, not a ReactFire problem. I realize you probably just had no better place to post it. [Our Google Group](https://groups.google.com/forum/#!forum/firebase-talk) or support@firebase.com are good places to do so in the future.

**Comment by olivierlesnicki** [comment]
I was using React-Native post 0.15. Will check it again and raise the issue again against the right outlet if possible.

**Comment by jwngr** [comment]
@olivierlesnicki - Did you have a chance to look into this again? I'm not sure if you opened the issue on a separate forum. If you did, please post a link to it here.

Ultimately, this is not a ReactFire issue, so I'm going to close it. There may in fact be an issue on our end, but that would be in the Firebase SDK itself. If you have more details to help us track this down, please reach out to [our Google Group](https://groups.google.com/forum/#!forum/firebase-talk) or firebase-support@google.com.
