### ISSUE TITLE
Hi, please i need help with this. "_firebase2.default is not a constructor"

### ISSUE THREAD

**Issue by yocmen** [firebase/reactfire#94]
i got this error when i run my react App:

`create.js?84fe:13 Uncaught TypeError: _firebase2.default is not a constructor`

just in the line when a create a new Firebase:

`const ref = new Firebase('https://my-project.firebaseio.com/');`

Can any one help me please, i use the latest version of firebase, reactfire, react-mixin

**Comment by jwngr** [comment]
What version of Firebase are you using? This library has not yet been upgraded to the just-released Firebase `3.x.x`. See #91 for details.

**Comment by wub** [comment]
You either need to:
- Downgrade to Firebase 2.X (force version in `package.json`) and continue as normal,
- Or [upgrade to the new Firebase](https://firebase.google.com/support/guides/firebase-web), and use `firebase.initializeApp()` instead of `new Firebase()` - but you'll probably have to wait for [ReactFire 1.0](https://github.com/firebase/reactfire/tree/1.0).

When you upgrade, also make sure you do `npm un --save firebase && npm i --save firebase` to clean up old versions.

**Comment by yocmen** [comment]
hoooo i see... i use Firebase 3, ok i will wait for the next release of the reactfire.... very thanksss to all!!!

**Comment by Jerry-Lau** [comment]
thanks!

**Comment by SorooshPardazCompany** [comment]
[اپلیکیشن خدمات منزل](http://doyo.ir) ,  [برنامه نویسی اندروید و آیفون](https://sorooshpardaz.com/mobile-app-android-ios-programming) , [برنامه نویسی موبایل](https://sorooshpardaz.com/mobile-app-android-ios-programming)
